- id: change_theme
  alias: "Change theme"
  description: "Change between light and dark theme when sunset or sunrise or the server starts"
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: "above_horizon"
    - platform: state
      entity_id: sun.sun
      to: "below_horizon"
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ 'clear' if is_state('sun.sun', 'above_horizon') else 'clear-dark' }}"

- id: telegram_send_message_on_xiaomi_mijia_flora_01_moisture_is_low
  alias: "Telegram send message ON mijia flora 01 moisture IS low"
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_mijia_flora_01_moisture
    below: 15
  action:
    service: telegram_bot.send_message
    data:
      message: "Por favor, riega la orquídea cuanto antes."

- id: turn_on_off_garage_blanket
  alias: "Turn on/off Garage Blanket"
  description: "Turn on/off Blitzwolf BW SHP2 when ESP32 (02) Temperature round Temperature Limit"
  trigger:
    - event_data:
        entity_id: sensor.esp32_02_temperature
      event_type: state_changed
      platform: event
  condition:
    - condition: template
      value_template: "{{ states('binary_sensor.blitzwolf_bw_shp2_switch_readonly') != ('on' if states('sensor.esp32_02_temperature') | int < states('input_number.blitzwolf_bw_shp2_temperature_limit') | int else 'off') }}"
  action:
    - service_template: "homeassistant.turn_{{ 'on' if states('sensor.esp32_02_temperature') | int < states('input_number.blitzwolf_bw_shp2_temperature_limit') | int else 'off' }}"
      data:
        entity_id: switch.blitzwolf_shp2_01_switch

- id: turn_on_the_heating_at_morning
  alias: "Turn on the heating at morning"
  description: "Set target temperature to home ON 05:30:00 IF automatic heating is enabled"
  trigger:
    - platform: time
      at: 05:30:00
  condition:
    - condition: state
      entity_id: climate.home_thermostat
      state: heat
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.home_thermostat
        hvac_mode: heat
        temperature: 22

- id: someone_is_ringing_the_doorbell
  alias: "Someone is ringing the doorbell"
  description: "Send notifications when someone's ringing the doorbell."
  trigger:
    - platform: state
      entity_id: binary_sensor.esp32_03_button
      from: "off"
      to: "on"
  action:
    - service: notify.webos_tv_lf652v
      data:
        message: "Han llamado al timbre."
    - service: notify.webos_tv_lm6300pla
      data:
        message: "Han llamado al timbre."
    - service: notify.mobile_app_oneplus_a5000
      data:
        message: "Han llamado al timbre."
    - service: notify.mobile_app_iphone_de_eva
      data:
        message: "Han llamado al timbre."